name: 'PR labeler based on multiple rules'
description: 'Label Pull Requests based on configurable rules'
author: 'Galo Navarro <anglorvaroa@gmail.com>'
inputs: 
  config_path:
    description: 'Path for labeling rules'
    default: '.github/labeler.yml'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/falbrechtskirchinger/labeler:master'
branding:
  icon: award
  color: blue
